name: Proof HTML
on:
  push:
  workflow_dispatch:
permissions: {}

jobs:
  build:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: anishathalye/proof-html@47a787591515a207d6fc8ef13e016ac42cb877c8 # v1.1.0
        with:
          directory: ./
